# Generated by Django 2.1.3 on 2018-11-11 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': '歌曲分类', 'verbose_name_plural': '歌曲分类'},
        ),
    ]
